services:
  ddddocr-api:
    container_name: ddddocr-api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true